### ISSUE TITLE
ttf file not found

### ISSUE THREAD

**Issue by pjc12345678** [DS4SD/MolDepictor#1]
I want to generate picture by this depictor, But I find that circled_large.ttf and circled.ttf not find.  How could I get these ttf file?  
hope for you reply.

**Comment by lucas-morin** [comment]
Hi @pjc12345678,

Sorry for the late reply.
I just added the .ttf files to the repository, [here](https://github.com/DS4SD/MolDepictor/tree/main/external/rdkit/Data/Fonts).

**Comment by pjc12345678** [comment]
thank you !!!   
feel free to close this issue
